ALTER TABLE dise_1213_basic_data
 ADD COLUMN class1_total_enr_boys integer,
 ADD COLUMN class2_total_enr_boys integer,
 ADD COLUMN class3_total_enr_boys integer,
 ADD COLUMN class4_total_enr_boys integer,
 ADD COLUMN class5_total_enr_boys integer,
 ADD COLUMN class6_total_enr_boys integer,
 ADD COLUMN class7_total_enr_boys integer,
 ADD COLUMN class8_total_enr_boys integer,
 ADD COLUMN class1_total_enr_girls integer,
 ADD COLUMN class2_total_enr_girls integer,
 ADD COLUMN class3_total_enr_girls integer,
 ADD COLUMN class4_total_enr_girls integer,
 ADD COLUMN class5_total_enr_girls integer,
 ADD COLUMN class6_total_enr_girls integer,
 ADD COLUMN class7_total_enr_girls integer,
 ADD COLUMN class8_total_enr_girls integer;
