# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20180104_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='dise1011blockaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1011clusteraggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1011districtaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1112blockaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1112clusteraggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1112districtaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1213blockaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1213clusteraggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1213districtaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1314blockaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1314clusteraggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1314districtaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1415blockaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1415clusteraggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1415districtaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1516blockaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1516clusteraggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1516districtaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1617blockaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1617clusteraggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='dise1617districtaggregations',
            name='state_name',
            field=models.CharField(max_length=35, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011assemblyaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011blockaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011clusteraggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011districtaggregations',
            name='district',
            field=models.CharField(max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011districtaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011parliamentaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011pincodeaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112assemblyaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112blockaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112clusteraggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112districtaggregations',
            name='district',
            field=models.CharField(max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112districtaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112parliamentaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112pincodeaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213assemblyaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213blockaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213clusteraggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213districtaggregations',
            name='district',
            field=models.CharField(max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213districtaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213parliamentaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213pincodeaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314assemblyaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314blockaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314clusteraggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314districtaggregations',
            name='district',
            field=models.CharField(max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314districtaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314parliamentaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314pincodeaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415assemblyaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415blockaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415clusteraggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415districtaggregations',
            name='district',
            field=models.CharField(max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415districtaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415parliamentaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415pincodeaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516assemblyaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516blockaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516clusteraggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516districtaggregations',
            name='district',
            field=models.CharField(max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516districtaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516parliamentaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516pincodeaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617assemblyaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617blockaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617clusteraggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617districtaggregations',
            name='district',
            field=models.CharField(max_length=50),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617districtaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617parliamentaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617pincodeaggregations',
            name='slug',
            field=models.CharField(max_length=200, serialize=False, primary_key=True),
            preserve_default=True,
        ),
    ]
