# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20180131_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='classrooms_require_major_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='classrooms_require_minor_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='classrooms_require_major_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='classrooms_require_minor_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='classrooms_require_major_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='classrooms_require_minor_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='classrooms_require_major_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='classrooms_require_minor_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='classrooms_require_major_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='classrooms_require_minor_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='classrooms_require_major_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='classrooms_require_minor_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='classrooms_require_major_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='classrooms_require_minor_repair',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (5, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
    ]
