# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20180322_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dise1718BasicData',
            fields=[
                ('school_code', models.BigIntegerField(serialize=False, primary_key=True)),
                ('centroid', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('district', models.CharField(max_length=50, blank=True)),
                ('school_name', models.CharField(max_length=200, blank=True)),
                ('block_name', models.CharField(max_length=50, blank=True)),
                ('cluster_name', models.CharField(max_length=50, blank=True)),
                ('village_name', models.CharField(max_length=50, blank=True)),
                ('assembly_name', models.CharField(max_length=35, blank=True)),
                ('parliament_name', models.CharField(max_length=35, blank=True)),
                ('pincode', models.IntegerField(null=True, blank=True)),
                ('new_pincode', models.IntegerField(null=True, blank=True)),
                ('rural_urban', models.IntegerField(blank=True, null=True, choices=[(1, b'Rural'), (2, b'Urban')])),
                ('medium_of_instruction', models.IntegerField(blank=True, null=True, choices=[(1, b'Assamese'), (2, b'Bengali'), (3, b'Gujarati'), (4, b'Hindi'), (5, b'Kannada'), (6, b'Kashmiri'), (7, b'Konkani'), (8, b'Malayalam'), (9, b'Manipuri'), (10, b'Marathi'), (11, b'Nepali'), (12, b'Odia'), (13, b'Punjabi'), (14, b'Sanskrit'), (15, b'Sindhi'), (16, b'Tamil'), (17, b'Telugu'), (18, b'Urdu'), (19, b'English'), (20, b'Bodo'), (21, b'Mising'), (22, b'Dogri'), (23, b'Khasi'), (24, b'Garo'), (25, b'Mizo'), (26, b'Bhutia'), (27, b'Lepcha'), (28, b'Limboo'), (29, b'French'), (98, b'Others'), (99, b'Others')])),
                ('distance_brc', models.FloatField(null=True, blank=True)),
                ('distance_crc', models.FloatField(null=True, blank=True)),
                ('yeur_estd', models.IntegerField(null=True, blank=True)),
                ('pre_pry_yn', models.IntegerField(null=True, blank=True)),
                ('residential_sch_yn', models.IntegerField(null=True, blank=True)),
                ('sch_management', models.IntegerField(blank=True, null=True, choices=[(1, b'Department of Education'), (2, b'Tribal/Social Welfare Department'), (3, b'Local body'), (4, b'Pvt. Aided'), (5, b'Pvt. Unaided'), (6, b'Others'), (7, b'Central Govt.'), (8, b'Unrecognised'), (9, b'Unknown'), (97, b'Madarsa recognized (by Wakf board/Madarsa Board)'), (98, b'Madarsa unrecognized')])),
                ('lowest_class', models.IntegerField(null=True, blank=True)),
                ('highest_class', models.IntegerField(null=True, blank=True)),
                ('sch_category', models.IntegerField(blank=True, null=True, choices=[(1, b'Primary only (1-5)'), (2, b'Primary With Upper Primary(1-8)'), (3, b'Primary with Upper Primary and Secondary and higher Secondary(1-12)'), (4, b'Upper Primary only(6-8)'), (5, b'Upper Primary with Secondary and higher Secondary(6-12)'), (6, b'Primary, with Upper Primary and Secondary(1-10)'), (7, b'Upper Primary with Secondary(6-10)'), (8, b'Secondary only(9 & 10)'), (9, b'Unknown'), (10, b'Secondary with Hr. Secondary(9-12) '), (11, b'Hr. Secondary only/Jr. College(11 & 12)')])),
                ('pre_pry_students', models.IntegerField(null=True, blank=True)),
                ('school_type', models.IntegerField(blank=True, null=True, choices=[(1, b'Boys'), (2, b'Girls'), (3, b'Co-educational')])),
                ('shift_school_yn', models.IntegerField(null=True, blank=True)),
                ('no_of_working_days', models.IntegerField(null=True, blank=True)),
                ('no_of_acad_inspection', models.IntegerField(null=True, blank=True)),
                ('residential_sch_type', models.IntegerField(null=True, blank=True)),
                ('pre_pry_teachers', models.IntegerField(null=True, blank=True)),
                ('visits_by_brc', models.IntegerField(null=True, blank=True)),
                ('visits_by_crc', models.IntegerField(null=True, blank=True)),
                ('school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('building_status', models.IntegerField(blank=True, null=True, choices=[(1, b'Private '), (2, b'Rented'), (3, b'Government'), (4, b'Government school in a rent free building'), (5, b'No Building'), (6, b'Dilapidated'), (7, b'Under Construction'), (9, b'Unknown')])),
                ('tot_clrooms', models.IntegerField(null=True, blank=True)),
                ('classrooms_in_good_condition', models.IntegerField(null=True, blank=True)),
                ('classrooms_require_major_repair', models.IntegerField(null=True, blank=True)),
                ('classrooms_require_minor_repair', models.IntegerField(null=True, blank=True)),
                ('other_rooms_in_good_cond', models.IntegerField(null=True, blank=True)),
                ('other_rooms_need_major_rep', models.IntegerField(null=True, blank=True)),
                ('other_rooms_need_minor_rep', models.IntegerField(null=True, blank=True)),
                ('toilet_common', models.IntegerField(null=True, blank=True)),
                ('toilet_boys', models.IntegerField(null=True, blank=True)),
                ('toilet_girls', models.IntegerField(null=True, blank=True)),
                ('kitchen_devices_grant', models.IntegerField(null=True, blank=True)),
                ('status_of_mdm', models.IntegerField(blank=True, null=True, choices=[(0, b'Not applicable'), (1, b'Not provided'), (2, b'Provided & prepared in school premises'), (3, b'Provided but not prepared in school premises'), (4, b'Unknown'), (9, b'Unknown')])),
                ('computer_aided_learnin_lab', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('separate_room_for_headmaster', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('electricity', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('boundary_wall', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Pucca'), (2, b'Pucca but broken'), (3, b'Barbed wire fencing'), (4, b'Hedges'), (5, b'No boundary wall'), (6, b'Others'), (7, b'Partial'), (8, b'Under Construction'), (9, b'Unknown'), (10, b'Unknown')])),
                ('library_yn', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('playground', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('blackboard', models.IntegerField(null=True, blank=True)),
                ('books_in_library', models.IntegerField(null=True, blank=True)),
                ('drinking_water', models.IntegerField(blank=True, null=True, choices=[(1, b'Hand pumps'), (2, b'Well'), (3, b'Tap water'), (4, b'others'), (5, b'none')])),
                ('medical_checkup', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('ramps', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('no_of_computers', models.IntegerField(null=True, blank=True)),
                ('male_tch', models.IntegerField(null=True, blank=True)),
                ('female_tch', models.IntegerField(null=True, blank=True)),
                ('noresp_tch', models.IntegerField(null=True, blank=True)),
                ('head_teacher', models.IntegerField(null=True, blank=True)),
                ('graduate_teachers', models.IntegerField(null=True, blank=True)),
                ('tch_with_professional_qualification', models.IntegerField(null=True, blank=True)),
                ('days_involved_in_non_tch_assgn', models.IntegerField(null=True, blank=True)),
                ('teachers_involved_in_non_tch_assgn', models.IntegerField(null=True, blank=True)),
                ('class1_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class2_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class3_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class4_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class5_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class6_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class7_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class8_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class1_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('class2_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('class3_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('class4_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('class5_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('class6_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('class7_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('class8_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('total_boys', models.IntegerField(null=True, blank=True)),
                ('total_girls', models.IntegerField(null=True, blank=True)),
                ('academic_year', models.CharField(max_length=35, blank=True)),
                ('state_name', models.CharField(max_length=35, blank=True)),
                ('city_name', models.CharField(max_length=50, blank=True)),
                ('habitat_name', models.CharField(max_length=50, blank=True)),
                ('muncipality_name', models.CharField(max_length=50, blank=True)),
                ('panchayat_name', models.CharField(max_length=50, blank=True)),
                ('panchayat_code', models.IntegerField(null=True, blank=True)),
                ('latitude_degrees', models.IntegerField(null=True, blank=True)),
                ('latitude_minutes', models.IntegerField(null=True, blank=True)),
                ('latitude_seconds', models.IntegerField(null=True, blank=True)),
                ('longitude_degrees', models.IntegerField(null=True, blank=True)),
                ('longitude_minutes', models.IntegerField(null=True, blank=True)),
                ('longitude_seconds', models.IntegerField(null=True, blank=True)),
                ('class9_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class10_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class11_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class12_total_enr_boys', models.IntegerField(null=True, blank=True)),
                ('class9_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('class10_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('class11_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('class12_total_enr_girls', models.IntegerField(null=True, blank=True)),
                ('school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('approachable_by_road', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('continuous_comprehensive_evaluation', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('pupil_cumulative_record_maitained', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('pupil_cumulative_record_shared', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('school_management_committee', models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')])),
                ('boys_appeared_primary_exam', models.IntegerField(null=True, blank=True)),
                ('girls_appeared_primary_exam', models.IntegerField(null=True, blank=True)),
                ('boys_appeared_upper_primary_exam', models.IntegerField(null=True, blank=True)),
                ('girls_appeared_upper_primary_exam', models.IntegerField(null=True, blank=True)),
                ('boys_passed_primary_exam', models.IntegerField(null=True, blank=True)),
                ('girls_passed_primary_exam', models.IntegerField(null=True, blank=True)),
                ('boys_passed_upper_primary_exam', models.IntegerField(null=True, blank=True)),
                ('girls_passed_upper_primary_exam', models.IntegerField(null=True, blank=True)),
                ('boys_more_sixty_percent_primary_exam', models.IntegerField(null=True, blank=True)),
                ('girls_more_sixty_percent_primary_exam', models.IntegerField(null=True, blank=True)),
                ('boys_more_sixty_percent_upper_primary_exam', models.IntegerField(null=True, blank=True)),
                ('girls_more_sixty_percent_upper_primary_exam', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'dise_1718_basic_data',
            },
            bases=(models.Model,),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='playground',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, null=True, choices=[(0, b'Not Applicable'), (1, b'Yes'), (2, b'No'), (3, b'Yes but not functional'), (4, b'Unknown'), (9, b'Unknown')]),
            preserve_default=True,
        ),
    ]
