# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20190930_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dise1718AssemblyAggregations',
            fields=[
                ('slug', models.CharField(max_length=200, serialize=False, primary_key=True)),
                ('centroid', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('sum_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_govt_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_rural_schools', models.BigIntegerField(null=True, blank=True)),
                ('avg_distance_brc', models.FloatField(null=True, blank=True)),
                ('avg_distance_crc', models.FloatField(null=True, blank=True)),
                ('sum_pre_primary_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_residential_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_pre_primary_students', models.BigIntegerField(null=True, blank=True)),
                ('avg_pre_primary_students', models.FloatField(null=True, blank=True)),
                ('sum_shift_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_working_days', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_working_days', models.FloatField(null=True, blank=True)),
                ('sum_no_of_acad_inspection', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_acad_inspection', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_brc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_brc', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_crc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_crc', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tot_clrooms', models.BigIntegerField(null=True, blank=True)),
                ('avg_tot_clrooms', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_in_good_condition', models.FloatField(null=True, blank=True)),
                ('sum_has_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('sum_classrooms_require_major_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_major_repair', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_require_minor_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_minor_repair', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_in_good_cond', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_in_good_cond', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_major_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_major_rep', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_minor_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_minor_rep', models.FloatField(null=True, blank=True)),
                ('sum_toilet_common', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_common', models.FloatField(null=True, blank=True)),
                ('sum_toilet_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_boys', models.FloatField(null=True, blank=True)),
                ('sum_toilet_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_girls', models.FloatField(null=True, blank=True)),
                ('sum_kitchen_devices_grant', models.BigIntegerField(null=True, blank=True)),
                ('avg_kitchen_devices_grant', models.FloatField(null=True, blank=True)),
                ('sum_has_mdm', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_cal_lab', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_separate_room_for_headmaster', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_electricity', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_boundary_wall', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_library', models.BigIntegerField(null=True, blank=True)),
                ('sum_books_in_library', models.BigIntegerField(null=True, blank=True)),
                ('avg_books_in_library', models.FloatField(null=True, blank=True)),
                ('sum_has_playground', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_blackboard', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_drinking_water', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_medical_checkup', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_ramps', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_computer', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_girls_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_computers', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_computers', models.FloatField(null=True, blank=True)),
                ('sum_male_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_male_tch', models.FloatField(null=True, blank=True)),
                ('sum_female_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_female_tch', models.FloatField(null=True, blank=True)),
                ('sum_noresp_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_noresp_tch', models.FloatField(null=True, blank=True)),
                ('sum_head_teacher', models.BigIntegerField(null=True, blank=True)),
                ('avg_head_teacher', models.FloatField(null=True, blank=True)),
                ('sum_graduate_teachers', models.BigIntegerField(null=True, blank=True)),
                ('avg_graduate_teachers', models.FloatField(null=True, blank=True)),
                ('sum_tch_with_professional_qualification', models.BigIntegerField(null=True, blank=True)),
                ('avg_tch_with_professional_qualification', models.FloatField(null=True, blank=True)),
                ('sum_days_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_days_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_teachers_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_teachers_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_boys', models.FloatField(null=True, blank=True)),
                ('sum_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_girls', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('assembly_name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'dise_1718_assembly_aggregations',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Dise1718BlockAggregations',
            fields=[
                ('slug', models.CharField(max_length=200, serialize=False, primary_key=True)),
                ('centroid', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('sum_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_govt_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_rural_schools', models.BigIntegerField(null=True, blank=True)),
                ('avg_distance_brc', models.FloatField(null=True, blank=True)),
                ('avg_distance_crc', models.FloatField(null=True, blank=True)),
                ('sum_pre_primary_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_residential_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_pre_primary_students', models.BigIntegerField(null=True, blank=True)),
                ('avg_pre_primary_students', models.FloatField(null=True, blank=True)),
                ('sum_shift_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_working_days', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_working_days', models.FloatField(null=True, blank=True)),
                ('sum_no_of_acad_inspection', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_acad_inspection', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_brc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_brc', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_crc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_crc', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tot_clrooms', models.BigIntegerField(null=True, blank=True)),
                ('avg_tot_clrooms', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_in_good_condition', models.FloatField(null=True, blank=True)),
                ('sum_has_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('sum_classrooms_require_major_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_major_repair', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_require_minor_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_minor_repair', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_in_good_cond', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_in_good_cond', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_major_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_major_rep', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_minor_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_minor_rep', models.FloatField(null=True, blank=True)),
                ('sum_toilet_common', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_common', models.FloatField(null=True, blank=True)),
                ('sum_toilet_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_boys', models.FloatField(null=True, blank=True)),
                ('sum_toilet_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_girls', models.FloatField(null=True, blank=True)),
                ('sum_kitchen_devices_grant', models.BigIntegerField(null=True, blank=True)),
                ('avg_kitchen_devices_grant', models.FloatField(null=True, blank=True)),
                ('sum_has_mdm', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_cal_lab', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_separate_room_for_headmaster', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_electricity', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_boundary_wall', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_library', models.BigIntegerField(null=True, blank=True)),
                ('sum_books_in_library', models.BigIntegerField(null=True, blank=True)),
                ('avg_books_in_library', models.FloatField(null=True, blank=True)),
                ('sum_has_playground', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_blackboard', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_drinking_water', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_medical_checkup', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_ramps', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_computer', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_girls_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_computers', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_computers', models.FloatField(null=True, blank=True)),
                ('sum_male_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_male_tch', models.FloatField(null=True, blank=True)),
                ('sum_female_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_female_tch', models.FloatField(null=True, blank=True)),
                ('sum_noresp_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_noresp_tch', models.FloatField(null=True, blank=True)),
                ('sum_head_teacher', models.BigIntegerField(null=True, blank=True)),
                ('avg_head_teacher', models.FloatField(null=True, blank=True)),
                ('sum_graduate_teachers', models.BigIntegerField(null=True, blank=True)),
                ('avg_graduate_teachers', models.FloatField(null=True, blank=True)),
                ('sum_tch_with_professional_qualification', models.BigIntegerField(null=True, blank=True)),
                ('avg_tch_with_professional_qualification', models.FloatField(null=True, blank=True)),
                ('sum_days_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_days_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_teachers_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_teachers_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_boys', models.FloatField(null=True, blank=True)),
                ('sum_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_girls', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('block_name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50, blank=True)),
                ('state_name', models.CharField(max_length=35, blank=True)),
            ],
            options={
                'db_table': 'dise_1718_block_aggregations',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Dise1718ClusterAggregations',
            fields=[
                ('slug', models.CharField(max_length=200, serialize=False, primary_key=True)),
                ('centroid', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('sum_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_govt_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_rural_schools', models.BigIntegerField(null=True, blank=True)),
                ('avg_distance_brc', models.FloatField(null=True, blank=True)),
                ('avg_distance_crc', models.FloatField(null=True, blank=True)),
                ('sum_pre_primary_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_residential_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_pre_primary_students', models.BigIntegerField(null=True, blank=True)),
                ('avg_pre_primary_students', models.FloatField(null=True, blank=True)),
                ('sum_shift_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_working_days', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_working_days', models.FloatField(null=True, blank=True)),
                ('sum_no_of_acad_inspection', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_acad_inspection', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_brc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_brc', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_crc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_crc', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tot_clrooms', models.BigIntegerField(null=True, blank=True)),
                ('avg_tot_clrooms', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_in_good_condition', models.FloatField(null=True, blank=True)),
                ('sum_has_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('sum_classrooms_require_major_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_major_repair', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_require_minor_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_minor_repair', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_in_good_cond', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_in_good_cond', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_major_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_major_rep', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_minor_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_minor_rep', models.FloatField(null=True, blank=True)),
                ('sum_toilet_common', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_common', models.FloatField(null=True, blank=True)),
                ('sum_toilet_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_boys', models.FloatField(null=True, blank=True)),
                ('sum_toilet_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_girls', models.FloatField(null=True, blank=True)),
                ('sum_kitchen_devices_grant', models.BigIntegerField(null=True, blank=True)),
                ('avg_kitchen_devices_grant', models.FloatField(null=True, blank=True)),
                ('sum_has_mdm', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_cal_lab', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_separate_room_for_headmaster', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_electricity', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_boundary_wall', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_library', models.BigIntegerField(null=True, blank=True)),
                ('sum_books_in_library', models.BigIntegerField(null=True, blank=True)),
                ('avg_books_in_library', models.FloatField(null=True, blank=True)),
                ('sum_has_playground', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_blackboard', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_drinking_water', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_medical_checkup', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_ramps', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_computer', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_girls_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_computers', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_computers', models.FloatField(null=True, blank=True)),
                ('sum_male_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_male_tch', models.FloatField(null=True, blank=True)),
                ('sum_female_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_female_tch', models.FloatField(null=True, blank=True)),
                ('sum_noresp_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_noresp_tch', models.FloatField(null=True, blank=True)),
                ('sum_head_teacher', models.BigIntegerField(null=True, blank=True)),
                ('avg_head_teacher', models.FloatField(null=True, blank=True)),
                ('sum_graduate_teachers', models.BigIntegerField(null=True, blank=True)),
                ('avg_graduate_teachers', models.FloatField(null=True, blank=True)),
                ('sum_tch_with_professional_qualification', models.BigIntegerField(null=True, blank=True)),
                ('avg_tch_with_professional_qualification', models.FloatField(null=True, blank=True)),
                ('sum_days_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_days_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_teachers_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_teachers_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_boys', models.FloatField(null=True, blank=True)),
                ('sum_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_girls', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('cluster_name', models.CharField(max_length=50)),
                ('block_name', models.CharField(max_length=50, blank=True)),
                ('district', models.CharField(max_length=50, blank=True)),
                ('state_name', models.CharField(max_length=35, blank=True)),
            ],
            options={
                'db_table': 'dise_1718_cluster_aggregations',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Dise1718DistrictAggregations',
            fields=[
                ('slug', models.CharField(max_length=200, serialize=False, primary_key=True)),
                ('centroid', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('sum_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_govt_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_rural_schools', models.BigIntegerField(null=True, blank=True)),
                ('avg_distance_brc', models.FloatField(null=True, blank=True)),
                ('avg_distance_crc', models.FloatField(null=True, blank=True)),
                ('sum_pre_primary_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_residential_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_pre_primary_students', models.BigIntegerField(null=True, blank=True)),
                ('avg_pre_primary_students', models.FloatField(null=True, blank=True)),
                ('sum_shift_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_working_days', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_working_days', models.FloatField(null=True, blank=True)),
                ('sum_no_of_acad_inspection', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_acad_inspection', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_brc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_brc', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_crc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_crc', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tot_clrooms', models.BigIntegerField(null=True, blank=True)),
                ('avg_tot_clrooms', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_in_good_condition', models.FloatField(null=True, blank=True)),
                ('sum_has_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('sum_classrooms_require_major_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_major_repair', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_require_minor_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_minor_repair', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_in_good_cond', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_in_good_cond', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_major_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_major_rep', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_minor_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_minor_rep', models.FloatField(null=True, blank=True)),
                ('sum_toilet_common', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_common', models.FloatField(null=True, blank=True)),
                ('sum_toilet_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_boys', models.FloatField(null=True, blank=True)),
                ('sum_toilet_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_girls', models.FloatField(null=True, blank=True)),
                ('sum_kitchen_devices_grant', models.BigIntegerField(null=True, blank=True)),
                ('avg_kitchen_devices_grant', models.FloatField(null=True, blank=True)),
                ('sum_has_mdm', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_cal_lab', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_separate_room_for_headmaster', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_electricity', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_boundary_wall', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_library', models.BigIntegerField(null=True, blank=True)),
                ('sum_books_in_library', models.BigIntegerField(null=True, blank=True)),
                ('avg_books_in_library', models.FloatField(null=True, blank=True)),
                ('sum_has_playground', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_blackboard', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_drinking_water', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_medical_checkup', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_ramps', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_computer', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_girls_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_computers', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_computers', models.FloatField(null=True, blank=True)),
                ('sum_male_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_male_tch', models.FloatField(null=True, blank=True)),
                ('sum_female_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_female_tch', models.FloatField(null=True, blank=True)),
                ('sum_noresp_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_noresp_tch', models.FloatField(null=True, blank=True)),
                ('sum_head_teacher', models.BigIntegerField(null=True, blank=True)),
                ('avg_head_teacher', models.FloatField(null=True, blank=True)),
                ('sum_graduate_teachers', models.BigIntegerField(null=True, blank=True)),
                ('avg_graduate_teachers', models.FloatField(null=True, blank=True)),
                ('sum_tch_with_professional_qualification', models.BigIntegerField(null=True, blank=True)),
                ('avg_tch_with_professional_qualification', models.FloatField(null=True, blank=True)),
                ('sum_days_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_days_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_teachers_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_teachers_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_boys', models.FloatField(null=True, blank=True)),
                ('sum_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_girls', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('district', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=35, blank=True)),
            ],
            options={
                'db_table': 'dise_1718_district_aggregations',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Dise1718ParliamentAggregations',
            fields=[
                ('slug', models.CharField(max_length=200, serialize=False, primary_key=True)),
                ('centroid', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('sum_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_govt_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_rural_schools', models.BigIntegerField(null=True, blank=True)),
                ('avg_distance_brc', models.FloatField(null=True, blank=True)),
                ('avg_distance_crc', models.FloatField(null=True, blank=True)),
                ('sum_pre_primary_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_residential_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_pre_primary_students', models.BigIntegerField(null=True, blank=True)),
                ('avg_pre_primary_students', models.FloatField(null=True, blank=True)),
                ('sum_shift_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_working_days', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_working_days', models.FloatField(null=True, blank=True)),
                ('sum_no_of_acad_inspection', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_acad_inspection', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_brc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_brc', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_crc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_crc', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tot_clrooms', models.BigIntegerField(null=True, blank=True)),
                ('avg_tot_clrooms', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_in_good_condition', models.FloatField(null=True, blank=True)),
                ('sum_has_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('sum_classrooms_require_major_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_major_repair', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_require_minor_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_minor_repair', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_in_good_cond', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_in_good_cond', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_major_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_major_rep', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_minor_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_minor_rep', models.FloatField(null=True, blank=True)),
                ('sum_toilet_common', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_common', models.FloatField(null=True, blank=True)),
                ('sum_toilet_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_boys', models.FloatField(null=True, blank=True)),
                ('sum_toilet_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_girls', models.FloatField(null=True, blank=True)),
                ('sum_kitchen_devices_grant', models.BigIntegerField(null=True, blank=True)),
                ('avg_kitchen_devices_grant', models.FloatField(null=True, blank=True)),
                ('sum_has_mdm', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_cal_lab', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_separate_room_for_headmaster', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_electricity', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_boundary_wall', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_library', models.BigIntegerField(null=True, blank=True)),
                ('sum_books_in_library', models.BigIntegerField(null=True, blank=True)),
                ('avg_books_in_library', models.FloatField(null=True, blank=True)),
                ('sum_has_playground', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_blackboard', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_drinking_water', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_medical_checkup', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_ramps', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_computer', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_girls_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_computers', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_computers', models.FloatField(null=True, blank=True)),
                ('sum_male_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_male_tch', models.FloatField(null=True, blank=True)),
                ('sum_female_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_female_tch', models.FloatField(null=True, blank=True)),
                ('sum_noresp_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_noresp_tch', models.FloatField(null=True, blank=True)),
                ('sum_head_teacher', models.BigIntegerField(null=True, blank=True)),
                ('avg_head_teacher', models.FloatField(null=True, blank=True)),
                ('sum_graduate_teachers', models.BigIntegerField(null=True, blank=True)),
                ('avg_graduate_teachers', models.FloatField(null=True, blank=True)),
                ('sum_tch_with_professional_qualification', models.BigIntegerField(null=True, blank=True)),
                ('avg_tch_with_professional_qualification', models.FloatField(null=True, blank=True)),
                ('sum_days_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_days_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_teachers_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_teachers_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_boys', models.FloatField(null=True, blank=True)),
                ('sum_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_girls', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('parliament_name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'dise_1718_parliament_aggregations',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Dise1718PincodeAggregations',
            fields=[
                ('slug', models.CharField(max_length=200, serialize=False, primary_key=True)),
                ('centroid', django.contrib.gis.db.models.fields.GeometryField(srid=4326, null=True, blank=True)),
                ('sum_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_govt_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_rural_schools', models.BigIntegerField(null=True, blank=True)),
                ('avg_distance_brc', models.FloatField(null=True, blank=True)),
                ('avg_distance_crc', models.FloatField(null=True, blank=True)),
                ('sum_pre_primary_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_residential_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_pre_primary_students', models.BigIntegerField(null=True, blank=True)),
                ('avg_pre_primary_students', models.FloatField(null=True, blank=True)),
                ('sum_shift_schools', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_working_days', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_working_days', models.FloatField(null=True, blank=True)),
                ('sum_no_of_acad_inspection', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_acad_inspection', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_brc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_brc', models.FloatField(null=True, blank=True)),
                ('sum_visits_by_crc', models.BigIntegerField(null=True, blank=True)),
                ('avg_visits_by_crc', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_dev_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_tlm_grant_expnd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_recd', models.FloatField(null=True, blank=True)),
                ('sum_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('avg_funds_from_students_expnd', models.FloatField(null=True, blank=True)),
                ('sum_tot_clrooms', models.BigIntegerField(null=True, blank=True)),
                ('avg_tot_clrooms', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_in_good_condition', models.FloatField(null=True, blank=True)),
                ('sum_has_classrooms_in_good_condition', models.BigIntegerField(null=True, blank=True)),
                ('sum_classrooms_require_major_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_major_repair', models.FloatField(null=True, blank=True)),
                ('sum_classrooms_require_minor_repair', models.BigIntegerField(null=True, blank=True)),
                ('avg_classrooms_require_minor_repair', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_in_good_cond', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_in_good_cond', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_major_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_major_rep', models.FloatField(null=True, blank=True)),
                ('sum_other_rooms_need_minor_rep', models.BigIntegerField(null=True, blank=True)),
                ('avg_other_rooms_need_minor_rep', models.FloatField(null=True, blank=True)),
                ('sum_toilet_common', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_common', models.FloatField(null=True, blank=True)),
                ('sum_toilet_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_boys', models.FloatField(null=True, blank=True)),
                ('sum_toilet_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_toilet_girls', models.FloatField(null=True, blank=True)),
                ('sum_kitchen_devices_grant', models.BigIntegerField(null=True, blank=True)),
                ('avg_kitchen_devices_grant', models.FloatField(null=True, blank=True)),
                ('sum_has_mdm', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_cal_lab', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_separate_room_for_headmaster', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_electricity', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_boundary_wall', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_library', models.BigIntegerField(null=True, blank=True)),
                ('sum_books_in_library', models.BigIntegerField(null=True, blank=True)),
                ('avg_books_in_library', models.FloatField(null=True, blank=True)),
                ('sum_has_playground', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_blackboard', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_drinking_water', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_medical_checkup', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_ramps', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_computer', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_has_girls_toilet', models.BigIntegerField(null=True, blank=True)),
                ('sum_no_of_computers', models.BigIntegerField(null=True, blank=True)),
                ('avg_no_of_computers', models.FloatField(null=True, blank=True)),
                ('sum_male_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_male_tch', models.FloatField(null=True, blank=True)),
                ('sum_female_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_female_tch', models.FloatField(null=True, blank=True)),
                ('sum_noresp_tch', models.BigIntegerField(null=True, blank=True)),
                ('avg_noresp_tch', models.FloatField(null=True, blank=True)),
                ('sum_head_teacher', models.BigIntegerField(null=True, blank=True)),
                ('avg_head_teacher', models.FloatField(null=True, blank=True)),
                ('sum_graduate_teachers', models.BigIntegerField(null=True, blank=True)),
                ('avg_graduate_teachers', models.FloatField(null=True, blank=True)),
                ('sum_tch_with_professional_qualification', models.BigIntegerField(null=True, blank=True)),
                ('avg_tch_with_professional_qualification', models.FloatField(null=True, blank=True)),
                ('sum_days_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_days_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_teachers_involved_in_non_tch_assgn', models.BigIntegerField(null=True, blank=True)),
                ('avg_teachers_involved_in_non_tch_assgn', models.FloatField(null=True, blank=True)),
                ('sum_boys', models.BigIntegerField(null=True, blank=True)),
                ('avg_boys', models.FloatField(null=True, blank=True)),
                ('sum_girls', models.BigIntegerField(null=True, blank=True)),
                ('avg_girls', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_recd', models.FloatField(null=True, blank=True)),
                ('sum_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('avg_school_maintain_grant_expnd', models.FloatField(null=True, blank=True)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'dise_1718_pincode_aggregations',
            },
            bases=(models.Model,),
        ),
    ]
