# Generated by Django 3.0.7 on 2020-06-23 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_dise1718assemblyaggregations_dise1718blockaggregations_dise1718clusteraggregations_dise1718districta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dise1011assemblyaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='boundary_wall',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Pucca'), (2, 'Pucca but broken'), (3, 'Barbed wire fencing'), (4, 'Hedges'), (5, 'No boundary wall'), (6, 'Others'), (7, 'Partial'), (8, 'Under Construction'), (9, 'Unknown'), (10, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='building_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Private '), (2, 'Rented'), (3, 'Government'), (4, 'Government school in a rent free building'), (5, 'No Building'), (6, 'Dilapidated'), (7, 'Under Construction'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='drinking_water',
            field=models.IntegerField(blank=True, choices=[(1, 'Hand pumps'), (2, 'Well'), (3, 'Tap water'), (4, 'others'), (5, 'none')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='medium_of_instruction',
            field=models.IntegerField(blank=True, choices=[(1, 'Assamese'), (2, 'Bengali'), (3, 'Gujarati'), (4, 'Hindi'), (5, 'Kannada'), (6, 'Kashmiri'), (7, 'Konkani'), (8, 'Malayalam'), (9, 'Manipuri'), (10, 'Marathi'), (11, 'Nepali'), (12, 'Odia'), (13, 'Punjabi'), (14, 'Sanskrit'), (15, 'Sindhi'), (16, 'Tamil'), (17, 'Telugu'), (18, 'Urdu'), (19, 'English'), (20, 'Bodo'), (21, 'Mising'), (22, 'Dogri'), (23, 'Khasi'), (24, 'Garo'), (25, 'Mizo'), (26, 'Bhutia'), (27, 'Lepcha'), (28, 'Limboo'), (29, 'French'), (98, 'Others'), (99, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='playground',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='rural_urban',
            field=models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Urban')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='sch_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Primary only (1-5)'), (2, 'Primary With Upper Primary(1-8)'), (3, 'Primary with Upper Primary and Secondary and higher Secondary(1-12)'), (4, 'Upper Primary only(6-8)'), (5, 'Upper Primary with Secondary and higher Secondary(6-12)'), (6, 'Primary, with Upper Primary and Secondary(1-10)'), (7, 'Upper Primary with Secondary(6-10)'), (8, 'Secondary only(9 & 10)'), (9, 'Unknown'), (10, 'Secondary with Hr. Secondary(9-12) '), (11, 'Hr. Secondary only/Jr. College(11 & 12)')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='sch_management',
            field=models.IntegerField(blank=True, choices=[(1, 'Department of Education'), (2, 'Tribal/Social Welfare Department'), (3, 'Local body'), (4, 'Pvt. Aided'), (5, 'Pvt. Unaided'), (6, 'Others'), (7, 'Central Govt.'), (8, 'Unrecognised'), (9, 'Unknown'), (97, 'Madarsa recognized (by Wakf board/Madarsa Board)'), (98, 'Madarsa unrecognized')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='school_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Boys'), (2, 'Girls'), (3, 'Co-educational')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011basicdata',
            name='status_of_mdm',
            field=models.IntegerField(blank=True, choices=[(0, 'Not applicable'), (1, 'Not provided'), (2, 'Provided & prepared in school premises'), (3, 'Provided but not prepared in school premises'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1011blockaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1011clusteraggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1011districtaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1011parliamentaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1011pincodeaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1112assemblyaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='boundary_wall',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Pucca'), (2, 'Pucca but broken'), (3, 'Barbed wire fencing'), (4, 'Hedges'), (5, 'No boundary wall'), (6, 'Others'), (7, 'Partial'), (8, 'Under Construction'), (9, 'Unknown'), (10, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='building_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Private '), (2, 'Rented'), (3, 'Government'), (4, 'Government school in a rent free building'), (5, 'No Building'), (6, 'Dilapidated'), (7, 'Under Construction'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='drinking_water',
            field=models.IntegerField(blank=True, choices=[(1, 'Hand pumps'), (2, 'Well'), (3, 'Tap water'), (4, 'others'), (5, 'none')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='medium_of_instruction',
            field=models.IntegerField(blank=True, choices=[(1, 'Assamese'), (2, 'Bengali'), (3, 'Gujarati'), (4, 'Hindi'), (5, 'Kannada'), (6, 'Kashmiri'), (7, 'Konkani'), (8, 'Malayalam'), (9, 'Manipuri'), (10, 'Marathi'), (11, 'Nepali'), (12, 'Odia'), (13, 'Punjabi'), (14, 'Sanskrit'), (15, 'Sindhi'), (16, 'Tamil'), (17, 'Telugu'), (18, 'Urdu'), (19, 'English'), (20, 'Bodo'), (21, 'Mising'), (22, 'Dogri'), (23, 'Khasi'), (24, 'Garo'), (25, 'Mizo'), (26, 'Bhutia'), (27, 'Lepcha'), (28, 'Limboo'), (29, 'French'), (98, 'Others'), (99, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='playground',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='rural_urban',
            field=models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Urban')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='sch_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Primary only (1-5)'), (2, 'Primary With Upper Primary(1-8)'), (3, 'Primary with Upper Primary and Secondary and higher Secondary(1-12)'), (4, 'Upper Primary only(6-8)'), (5, 'Upper Primary with Secondary and higher Secondary(6-12)'), (6, 'Primary, with Upper Primary and Secondary(1-10)'), (7, 'Upper Primary with Secondary(6-10)'), (8, 'Secondary only(9 & 10)'), (9, 'Unknown'), (10, 'Secondary with Hr. Secondary(9-12) '), (11, 'Hr. Secondary only/Jr. College(11 & 12)')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='sch_management',
            field=models.IntegerField(blank=True, choices=[(1, 'Department of Education'), (2, 'Tribal/Social Welfare Department'), (3, 'Local body'), (4, 'Pvt. Aided'), (5, 'Pvt. Unaided'), (6, 'Others'), (7, 'Central Govt.'), (8, 'Unrecognised'), (9, 'Unknown'), (97, 'Madarsa recognized (by Wakf board/Madarsa Board)'), (98, 'Madarsa unrecognized')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='school_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Boys'), (2, 'Girls'), (3, 'Co-educational')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112basicdata',
            name='status_of_mdm',
            field=models.IntegerField(blank=True, choices=[(0, 'Not applicable'), (1, 'Not provided'), (2, 'Provided & prepared in school premises'), (3, 'Provided but not prepared in school premises'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1112blockaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1112clusteraggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1112districtaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1112parliamentaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1112pincodeaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1213assemblyaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='boundary_wall',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Pucca'), (2, 'Pucca but broken'), (3, 'Barbed wire fencing'), (4, 'Hedges'), (5, 'No boundary wall'), (6, 'Others'), (7, 'Partial'), (8, 'Under Construction'), (9, 'Unknown'), (10, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='building_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Private '), (2, 'Rented'), (3, 'Government'), (4, 'Government school in a rent free building'), (5, 'No Building'), (6, 'Dilapidated'), (7, 'Under Construction'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='drinking_water',
            field=models.IntegerField(blank=True, choices=[(1, 'Hand pumps'), (2, 'Well'), (3, 'Tap water'), (4, 'others'), (5, 'none')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='medium_of_instruction',
            field=models.IntegerField(blank=True, choices=[(1, 'Assamese'), (2, 'Bengali'), (3, 'Gujarati'), (4, 'Hindi'), (5, 'Kannada'), (6, 'Kashmiri'), (7, 'Konkani'), (8, 'Malayalam'), (9, 'Manipuri'), (10, 'Marathi'), (11, 'Nepali'), (12, 'Odia'), (13, 'Punjabi'), (14, 'Sanskrit'), (15, 'Sindhi'), (16, 'Tamil'), (17, 'Telugu'), (18, 'Urdu'), (19, 'English'), (20, 'Bodo'), (21, 'Mising'), (22, 'Dogri'), (23, 'Khasi'), (24, 'Garo'), (25, 'Mizo'), (26, 'Bhutia'), (27, 'Lepcha'), (28, 'Limboo'), (29, 'French'), (98, 'Others'), (99, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='playground',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='rural_urban',
            field=models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Urban')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='sch_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Primary only (1-5)'), (2, 'Primary With Upper Primary(1-8)'), (3, 'Primary with Upper Primary and Secondary and higher Secondary(1-12)'), (4, 'Upper Primary only(6-8)'), (5, 'Upper Primary with Secondary and higher Secondary(6-12)'), (6, 'Primary, with Upper Primary and Secondary(1-10)'), (7, 'Upper Primary with Secondary(6-10)'), (8, 'Secondary only(9 & 10)'), (9, 'Unknown'), (10, 'Secondary with Hr. Secondary(9-12) '), (11, 'Hr. Secondary only/Jr. College(11 & 12)')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='sch_management',
            field=models.IntegerField(blank=True, choices=[(1, 'Department of Education'), (2, 'Tribal/Social Welfare Department'), (3, 'Local body'), (4, 'Pvt. Aided'), (5, 'Pvt. Unaided'), (6, 'Others'), (7, 'Central Govt.'), (8, 'Unrecognised'), (9, 'Unknown'), (97, 'Madarsa recognized (by Wakf board/Madarsa Board)'), (98, 'Madarsa unrecognized')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='school_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Boys'), (2, 'Girls'), (3, 'Co-educational')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213basicdata',
            name='status_of_mdm',
            field=models.IntegerField(blank=True, choices=[(0, 'Not applicable'), (1, 'Not provided'), (2, 'Provided & prepared in school premises'), (3, 'Provided but not prepared in school premises'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1213blockaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1213clusteraggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1213districtaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1213parliamentaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1213pincodeaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1314assemblyaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='boundary_wall',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Pucca'), (2, 'Pucca but broken'), (3, 'Barbed wire fencing'), (4, 'Hedges'), (5, 'No boundary wall'), (6, 'Others'), (7, 'Partial'), (8, 'Under Construction'), (9, 'Unknown'), (10, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='building_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Private '), (2, 'Rented'), (3, 'Government'), (4, 'Government school in a rent free building'), (5, 'No Building'), (6, 'Dilapidated'), (7, 'Under Construction'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='drinking_water',
            field=models.IntegerField(blank=True, choices=[(1, 'Hand pumps'), (2, 'Well'), (3, 'Tap water'), (4, 'others'), (5, 'none')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='medium_of_instruction',
            field=models.IntegerField(blank=True, choices=[(1, 'Assamese'), (2, 'Bengali'), (3, 'Gujarati'), (4, 'Hindi'), (5, 'Kannada'), (6, 'Kashmiri'), (7, 'Konkani'), (8, 'Malayalam'), (9, 'Manipuri'), (10, 'Marathi'), (11, 'Nepali'), (12, 'Odia'), (13, 'Punjabi'), (14, 'Sanskrit'), (15, 'Sindhi'), (16, 'Tamil'), (17, 'Telugu'), (18, 'Urdu'), (19, 'English'), (20, 'Bodo'), (21, 'Mising'), (22, 'Dogri'), (23, 'Khasi'), (24, 'Garo'), (25, 'Mizo'), (26, 'Bhutia'), (27, 'Lepcha'), (28, 'Limboo'), (29, 'French'), (98, 'Others'), (99, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='playground',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='rural_urban',
            field=models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Urban')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='sch_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Primary only (1-5)'), (2, 'Primary With Upper Primary(1-8)'), (3, 'Primary with Upper Primary and Secondary and higher Secondary(1-12)'), (4, 'Upper Primary only(6-8)'), (5, 'Upper Primary with Secondary and higher Secondary(6-12)'), (6, 'Primary, with Upper Primary and Secondary(1-10)'), (7, 'Upper Primary with Secondary(6-10)'), (8, 'Secondary only(9 & 10)'), (9, 'Unknown'), (10, 'Secondary with Hr. Secondary(9-12) '), (11, 'Hr. Secondary only/Jr. College(11 & 12)')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='sch_management',
            field=models.IntegerField(blank=True, choices=[(1, 'Department of Education'), (2, 'Tribal/Social Welfare Department'), (3, 'Local body'), (4, 'Pvt. Aided'), (5, 'Pvt. Unaided'), (6, 'Others'), (7, 'Central Govt.'), (8, 'Unrecognised'), (9, 'Unknown'), (97, 'Madarsa recognized (by Wakf board/Madarsa Board)'), (98, 'Madarsa unrecognized')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='school_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Boys'), (2, 'Girls'), (3, 'Co-educational')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314basicdata',
            name='status_of_mdm',
            field=models.IntegerField(blank=True, choices=[(0, 'Not applicable'), (1, 'Not provided'), (2, 'Provided & prepared in school premises'), (3, 'Provided but not prepared in school premises'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1314blockaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1314clusteraggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1314districtaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1314parliamentaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1314pincodeaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1415assemblyaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='boundary_wall',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Pucca'), (2, 'Pucca but broken'), (3, 'Barbed wire fencing'), (4, 'Hedges'), (5, 'No boundary wall'), (6, 'Others'), (7, 'Partial'), (8, 'Under Construction'), (9, 'Unknown'), (10, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='building_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Private '), (2, 'Rented'), (3, 'Government'), (4, 'Government school in a rent free building'), (5, 'No Building'), (6, 'Dilapidated'), (7, 'Under Construction'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='drinking_water',
            field=models.IntegerField(blank=True, choices=[(1, 'Hand pumps'), (2, 'Well'), (3, 'Tap water'), (4, 'others'), (5, 'none')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='medium_of_instruction',
            field=models.IntegerField(blank=True, choices=[(1, 'Assamese'), (2, 'Bengali'), (3, 'Gujarati'), (4, 'Hindi'), (5, 'Kannada'), (6, 'Kashmiri'), (7, 'Konkani'), (8, 'Malayalam'), (9, 'Manipuri'), (10, 'Marathi'), (11, 'Nepali'), (12, 'Odia'), (13, 'Punjabi'), (14, 'Sanskrit'), (15, 'Sindhi'), (16, 'Tamil'), (17, 'Telugu'), (18, 'Urdu'), (19, 'English'), (20, 'Bodo'), (21, 'Mising'), (22, 'Dogri'), (23, 'Khasi'), (24, 'Garo'), (25, 'Mizo'), (26, 'Bhutia'), (27, 'Lepcha'), (28, 'Limboo'), (29, 'French'), (98, 'Others'), (99, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='playground',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='rural_urban',
            field=models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Urban')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='sch_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Primary only (1-5)'), (2, 'Primary With Upper Primary(1-8)'), (3, 'Primary with Upper Primary and Secondary and higher Secondary(1-12)'), (4, 'Upper Primary only(6-8)'), (5, 'Upper Primary with Secondary and higher Secondary(6-12)'), (6, 'Primary, with Upper Primary and Secondary(1-10)'), (7, 'Upper Primary with Secondary(6-10)'), (8, 'Secondary only(9 & 10)'), (9, 'Unknown'), (10, 'Secondary with Hr. Secondary(9-12) '), (11, 'Hr. Secondary only/Jr. College(11 & 12)')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='sch_management',
            field=models.IntegerField(blank=True, choices=[(1, 'Department of Education'), (2, 'Tribal/Social Welfare Department'), (3, 'Local body'), (4, 'Pvt. Aided'), (5, 'Pvt. Unaided'), (6, 'Others'), (7, 'Central Govt.'), (8, 'Unrecognised'), (9, 'Unknown'), (97, 'Madarsa recognized (by Wakf board/Madarsa Board)'), (98, 'Madarsa unrecognized')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='school_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Boys'), (2, 'Girls'), (3, 'Co-educational')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415basicdata',
            name='status_of_mdm',
            field=models.IntegerField(blank=True, choices=[(0, 'Not applicable'), (1, 'Not provided'), (2, 'Provided & prepared in school premises'), (3, 'Provided but not prepared in school premises'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1415blockaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1415clusteraggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1415districtaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1415parliamentaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1415pincodeaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1516assemblyaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='boundary_wall',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Pucca'), (2, 'Pucca but broken'), (3, 'Barbed wire fencing'), (4, 'Hedges'), (5, 'No boundary wall'), (6, 'Others'), (7, 'Partial'), (8, 'Under Construction'), (9, 'Unknown'), (10, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='building_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Private '), (2, 'Rented'), (3, 'Government'), (4, 'Government school in a rent free building'), (5, 'No Building'), (6, 'Dilapidated'), (7, 'Under Construction'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='drinking_water',
            field=models.IntegerField(blank=True, choices=[(1, 'Hand pumps'), (2, 'Well'), (3, 'Tap water'), (4, 'others'), (5, 'none')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='medium_of_instruction',
            field=models.IntegerField(blank=True, choices=[(1, 'Assamese'), (2, 'Bengali'), (3, 'Gujarati'), (4, 'Hindi'), (5, 'Kannada'), (6, 'Kashmiri'), (7, 'Konkani'), (8, 'Malayalam'), (9, 'Manipuri'), (10, 'Marathi'), (11, 'Nepali'), (12, 'Odia'), (13, 'Punjabi'), (14, 'Sanskrit'), (15, 'Sindhi'), (16, 'Tamil'), (17, 'Telugu'), (18, 'Urdu'), (19, 'English'), (20, 'Bodo'), (21, 'Mising'), (22, 'Dogri'), (23, 'Khasi'), (24, 'Garo'), (25, 'Mizo'), (26, 'Bhutia'), (27, 'Lepcha'), (28, 'Limboo'), (29, 'French'), (98, 'Others'), (99, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='playground',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='rural_urban',
            field=models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Urban')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='sch_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Primary only (1-5)'), (2, 'Primary With Upper Primary(1-8)'), (3, 'Primary with Upper Primary and Secondary and higher Secondary(1-12)'), (4, 'Upper Primary only(6-8)'), (5, 'Upper Primary with Secondary and higher Secondary(6-12)'), (6, 'Primary, with Upper Primary and Secondary(1-10)'), (7, 'Upper Primary with Secondary(6-10)'), (8, 'Secondary only(9 & 10)'), (9, 'Unknown'), (10, 'Secondary with Hr. Secondary(9-12) '), (11, 'Hr. Secondary only/Jr. College(11 & 12)')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='sch_management',
            field=models.IntegerField(blank=True, choices=[(1, 'Department of Education'), (2, 'Tribal/Social Welfare Department'), (3, 'Local body'), (4, 'Pvt. Aided'), (5, 'Pvt. Unaided'), (6, 'Others'), (7, 'Central Govt.'), (8, 'Unrecognised'), (9, 'Unknown'), (97, 'Madarsa recognized (by Wakf board/Madarsa Board)'), (98, 'Madarsa unrecognized')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='school_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Boys'), (2, 'Girls'), (3, 'Co-educational')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516basicdata',
            name='status_of_mdm',
            field=models.IntegerField(blank=True, choices=[(0, 'Not applicable'), (1, 'Not provided'), (2, 'Provided & prepared in school premises'), (3, 'Provided but not prepared in school premises'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1516blockaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1516clusteraggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1516districtaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1516parliamentaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1516pincodeaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1617assemblyaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='boundary_wall',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Pucca'), (2, 'Pucca but broken'), (3, 'Barbed wire fencing'), (4, 'Hedges'), (5, 'No boundary wall'), (6, 'Others'), (7, 'Partial'), (8, 'Under Construction'), (9, 'Unknown'), (10, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='building_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Private '), (2, 'Rented'), (3, 'Government'), (4, 'Government school in a rent free building'), (5, 'No Building'), (6, 'Dilapidated'), (7, 'Under Construction'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='drinking_water',
            field=models.IntegerField(blank=True, choices=[(1, 'Hand pumps'), (2, 'Well'), (3, 'Tap water'), (4, 'others'), (5, 'none')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='medium_of_instruction',
            field=models.IntegerField(blank=True, choices=[(1, 'Assamese'), (2, 'Bengali'), (3, 'Gujarati'), (4, 'Hindi'), (5, 'Kannada'), (6, 'Kashmiri'), (7, 'Konkani'), (8, 'Malayalam'), (9, 'Manipuri'), (10, 'Marathi'), (11, 'Nepali'), (12, 'Odia'), (13, 'Punjabi'), (14, 'Sanskrit'), (15, 'Sindhi'), (16, 'Tamil'), (17, 'Telugu'), (18, 'Urdu'), (19, 'English'), (20, 'Bodo'), (21, 'Mising'), (22, 'Dogri'), (23, 'Khasi'), (24, 'Garo'), (25, 'Mizo'), (26, 'Bhutia'), (27, 'Lepcha'), (28, 'Limboo'), (29, 'French'), (98, 'Others'), (99, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='playground',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='rural_urban',
            field=models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Urban')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='sch_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Primary only (1-5)'), (2, 'Primary With Upper Primary(1-8)'), (3, 'Primary with Upper Primary and Secondary and higher Secondary(1-12)'), (4, 'Upper Primary only(6-8)'), (5, 'Upper Primary with Secondary and higher Secondary(6-12)'), (6, 'Primary, with Upper Primary and Secondary(1-10)'), (7, 'Upper Primary with Secondary(6-10)'), (8, 'Secondary only(9 & 10)'), (9, 'Unknown'), (10, 'Secondary with Hr. Secondary(9-12) '), (11, 'Hr. Secondary only/Jr. College(11 & 12)')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='sch_management',
            field=models.IntegerField(blank=True, choices=[(1, 'Department of Education'), (2, 'Tribal/Social Welfare Department'), (3, 'Local body'), (4, 'Pvt. Aided'), (5, 'Pvt. Unaided'), (6, 'Others'), (7, 'Central Govt.'), (8, 'Unrecognised'), (9, 'Unknown'), (97, 'Madarsa recognized (by Wakf board/Madarsa Board)'), (98, 'Madarsa unrecognized')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='school_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Boys'), (2, 'Girls'), (3, 'Co-educational')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617basicdata',
            name='status_of_mdm',
            field=models.IntegerField(blank=True, choices=[(0, 'Not applicable'), (1, 'Not provided'), (2, 'Provided & prepared in school premises'), (3, 'Provided but not prepared in school premises'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1617blockaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1617clusteraggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1617districtaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1617parliamentaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1617pincodeaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1718assemblyaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='approachable_by_road',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='boundary_wall',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Pucca'), (2, 'Pucca but broken'), (3, 'Barbed wire fencing'), (4, 'Hedges'), (5, 'No boundary wall'), (6, 'Others'), (7, 'Partial'), (8, 'Under Construction'), (9, 'Unknown'), (10, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='building_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Private '), (2, 'Rented'), (3, 'Government'), (4, 'Government school in a rent free building'), (5, 'No Building'), (6, 'Dilapidated'), (7, 'Under Construction'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='computer_aided_learnin_lab',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='continuous_comprehensive_evaluation',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='drinking_water',
            field=models.IntegerField(blank=True, choices=[(1, 'Hand pumps'), (2, 'Well'), (3, 'Tap water'), (4, 'others'), (5, 'none')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='electricity',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='library_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='medical_checkup',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='medium_of_instruction',
            field=models.IntegerField(blank=True, choices=[(1, 'Assamese'), (2, 'Bengali'), (3, 'Gujarati'), (4, 'Hindi'), (5, 'Kannada'), (6, 'Kashmiri'), (7, 'Konkani'), (8, 'Malayalam'), (9, 'Manipuri'), (10, 'Marathi'), (11, 'Nepali'), (12, 'Odia'), (13, 'Punjabi'), (14, 'Sanskrit'), (15, 'Sindhi'), (16, 'Tamil'), (17, 'Telugu'), (18, 'Urdu'), (19, 'English'), (20, 'Bodo'), (21, 'Mising'), (22, 'Dogri'), (23, 'Khasi'), (24, 'Garo'), (25, 'Mizo'), (26, 'Bhutia'), (27, 'Lepcha'), (28, 'Limboo'), (29, 'French'), (98, 'Others'), (99, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='playground',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='pupil_cumulative_record_maitained',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='pupil_cumulative_record_shared',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='ramps',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='rural_urban',
            field=models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Urban')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='sch_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Primary only (1-5)'), (2, 'Primary With Upper Primary(1-8)'), (3, 'Primary with Upper Primary and Secondary and higher Secondary(1-12)'), (4, 'Upper Primary only(6-8)'), (5, 'Upper Primary with Secondary and higher Secondary(6-12)'), (6, 'Primary, with Upper Primary and Secondary(1-10)'), (7, 'Upper Primary with Secondary(6-10)'), (8, 'Secondary only(9 & 10)'), (9, 'Unknown'), (10, 'Secondary with Hr. Secondary(9-12) '), (11, 'Hr. Secondary only/Jr. College(11 & 12)')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='sch_management',
            field=models.IntegerField(blank=True, choices=[(1, 'Department of Education'), (2, 'Tribal/Social Welfare Department'), (3, 'Local body'), (4, 'Pvt. Aided'), (5, 'Pvt. Unaided'), (6, 'Others'), (7, 'Central Govt.'), (8, 'Unrecognised'), (9, 'Unknown'), (97, 'Madarsa recognized (by Wakf board/Madarsa Board)'), (98, 'Madarsa unrecognized')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='school_management_committee',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='school_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Boys'), (2, 'Girls'), (3, 'Co-educational')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='separate_room_for_headmaster',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Applicable'), (1, 'Yes'), (2, 'No'), (3, 'Yes but not functional'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718basicdata',
            name='status_of_mdm',
            field=models.IntegerField(blank=True, choices=[(0, 'Not applicable'), (1, 'Not provided'), (2, 'Provided & prepared in school premises'), (3, 'Provided but not prepared in school premises'), (4, 'Unknown'), (9, 'Unknown')], null=True),
        ),
        migrations.AlterField(
            model_name='dise1718blockaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1718clusteraggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1718districtaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1718parliamentaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='dise1718pincodeaggregations',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, unique=True),
        ),
    ]
